require 'rubygems'

Gem::manage_gems

require 'rake/gempackagetask'
require 'rake/rdoctask'

spec = Gem::Specification.new do |s|
  s.name     = 'crackup-ftp'
  s.version  = '1.0.2'
  s.author   = 'Ryan Grove'
  s.email    = 'ryan@wonko.com'
  s.homepage = 'http://wonko.com/software/crackup'
  s.platform = Gem::Platform::RUBY
  s.summary  = "FTP storage driver for Crackup."

  s.files        = FileList['lib/**/*', 'LICENSE'].exclude('rdoc').to_a
  s.require_path = 'lib'

  s.has_rdoc         = true
  s.extra_rdoc_files = ['LICENSE']
  
  s.required_ruby_version = '>= 1.8.4'
  s.add_dependency('crackup', '= 1.0.2')
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = true
end

Rake::RDocTask.new do |rd|
  rd.rdoc_dir = 'doc/html'
  rd.rdoc_files.include('lib/**/*.rb')
end
